packages:
  - .

allowBuilds:
  msw: true
  sharp: true
  unrs-resolver: true
  esbuild: true
  workerd: true

patchedDependencies:
  '@opennextjs/cloudflare@1.20.2': patches/@opennextjs__cloudflare@1.20.2.patch
