/**
 * One-time data migration: export live Supabase rows for case_studies, services,
 * and video_projects into a D1-compatible .sql file (INSERT statements with JSON
 * columns stringified, single quotes escaped). Run once, then apply the output
 * with `wrangler d1 execute propagenda-cms --remote --file d1/seed-from-supabase.sql`.
 *
 * This exports whatever is LIVE in Supabase right now (the source of truth for the
 * migration), not the content/*.ts seed files, so any drift between the two is
 * resolved in Supabase's favor -- matching TASK-11.2's "row-for-row" acceptance
 * criterion.
 */
import { writeFileSync } from 'node:fs';
import { createClient } from '@supabase/supabase-js';

for (const file of ['.env', '.env.local']) {
  try {
    process.loadEnvFile(file);
  } catch {
    // missing file is fine
  }
}

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error('Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.');
  process.exit(1);
}

const supabase = createClient(url, key, { auth: { persistSession: false } });

// Columns per table, in the exact order the D1 migration declares them (minus the
// autoincrement id, which D1 assigns fresh -- prev_slug/next_slug still reference
// slugs, not ids, so this is safe).
const TABLES: Record<string, string[]> = {
  services: [
    'slug', 'locale', 'status', 'sort_order', 'title', 'h1', 'overview',
    'scope_items', 'gallery', 'seo', 'tiers', 'event_checklist', 'extended_bullets',
    'related_work', 'tertiary_cta', 'hub', 'published_at', 'created_at', 'updated_at',
  ],
  case_studies: [
    'slug', 'locale', 'status', 'sort_order', 'title', 'h1', 'tier', 'category',
    'overview', 'scope_items', 'gallery', 'seo', 'client', 'industry', 'year',
    'hero_image', 'deliverables', 'results', 'challenge', 'approach', 'outcome',
    'quote', 'accent', 'prev_slug', 'next_slug', 'published_at', 'created_at', 'updated_at',
  ],
  video_projects: [
    'slug', 'locale', 'status', 'sort_order', 'is_showreel', 'title', 'category',
    'src', 'poster', 'orientation', 'width', 'height', 'duration', 'client',
    'description', 'placeholder', 'published_at', 'created_at', 'updated_at',
  ],
};

const JSON_COLUMNS = new Set([
  'scope_items', 'gallery', 'seo', 'tiers', 'event_checklist', 'extended_bullets',
  'related_work', 'tertiary_cta', 'hub', 'deliverables', 'results', 'quote', 'accent',
]);

function sqlValue(col: string, value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (JSON_COLUMNS.has(col)) return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
  if (typeof value === 'boolean') return value ? '1' : '0';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

async function main() {
  const lines: string[] = [
    '-- Generated by scripts/export-supabase-to-d1.ts -- one-time data import.',
    '-- Exported live from Supabase, not from content/*.ts, per TASK-11.2.',
    '',
  ];
  const counts: Record<string, number> = {};

  for (const [table, columns] of Object.entries(TABLES)) {
    const { data, error } = await supabase.from(table).select('*').order('sort_order');
    if (error) throw new Error(`${table}: ${error.message}`);
    counts[table] = data?.length ?? 0;

    for (const row of data ?? []) {
      const cols = columns.join(', ');
      const vals = columns.map((c) => sqlValue(c, (row as Record<string, unknown>)[c])).join(', ');
      lines.push(`INSERT INTO ${table} (${cols}) VALUES (${vals});`);
    }
    lines.push('');
  }

  writeFileSync('d1/seed-from-supabase.sql', lines.join('\n'));
  console.log('Wrote d1/seed-from-supabase.sql. Row counts:', counts);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
